name: Documentation Issue
description: Report issues with documentation or request documentation improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Improvement

        Good documentation is essential for project success. Help us improve by reporting:
        - Missing documentation
        - Outdated information
        - Confusing explanations
        - Broken links or examples
        - Gaps in coverage

        **Documentation Standards**: See `.claude/rules/documentation-guide.md` for our documentation principles.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
        - label: I have checked if similar documentation issues exist
          required: true
        - label: I have verified the information is actually incorrect or missing
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: Which type of documentation needs improvement?
      options:
        - README / Getting Started
        - API Documentation
        - Code Comments / JSDoc
        - Architecture Documentation (ADR)
        - Deployment / Operations (Runbooks)
        - User Guide / Tutorial
        - Troubleshooting Guide
        - Development Guidelines (.claude/rules/)
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing - No documentation exists
        - Incorrect - Information is wrong
        - Outdated - Information is no longer accurate
        - Unclear - Confusing or poorly explained
        - Incomplete - Documentation exists but gaps remain
        - Broken - Links, examples, or code don't work
        - Improvement - Good but could be better
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is (or should be) the documentation?
      placeholder: "Example: README.md, .claude/rules/express.md, API docs at /api/users endpoint"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What's Wrong or Missing?
      description: Describe the documentation issue clearly
      placeholder: |
        Example: The README.md says to run `npm start` but that script doesn't exist in package.json. The actual command is `npm run dev`.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What Should Be Documented?
      description: What information should be present or correct?
      placeholder: |
        Example: The README should document:
        1. Available npm scripts (dev, build, test, lint)
        2. What each script does
        3. When to use each script
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: |
        Who is affected by this documentation issue?
        How does it affect them?
      placeholder: |
        Example:
        - Affects: New developers trying to run the project
        - Impact: Wastes 10-15 minutes trying wrong command, causes confusion
        - Frequency: Every new team member encounters this

  - type: textarea
    id: current-content
    attributes:
      label: Current Content (if applicable)
      description: Quote the existing documentation that needs fixing
      render: markdown
      placeholder: |
        ```
        ## Getting Started

        Run `npm start` to start the development server.
        ```

  - type: textarea
    id: proposed-content
    attributes:
      label: Proposed Content
      description: Suggest how the documentation should be written
      render: markdown
      placeholder: |
        ```
        ## Getting Started

        Run the development server:

        \`\`\`bash
        npm run dev
        \`\`\`

        The server will start on http://localhost:3000 with hot-reloading enabled.

        ### Available Scripts

        - `npm run dev` - Start development server with hot-reload
        - `npm run build` - Build for production
        - `npm test` - Run test suite
        - `npm run lint` - Check code quality
        \`\`\`

  - type: textarea
    id: examples
    attributes:
      label: Examples Needed
      description: Should this documentation include code examples?
      placeholder: |
        Example: Yes, add example showing:
        1. Starting the dev server
        2. Running tests
        3. Building for production

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this documentation fix?
      options:
        - Critical - Blocks onboarding or causes major confusion
        - High - Important information missing or wrong
        - Medium - Useful improvement
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: related-docs
    attributes:
      label: Related Documentation
      description: |
        Are there related documentation sections that should also be updated?
        Link to other relevant docs or issues.
      placeholder: |
        Example:
        - Also affects: .claude/rules/nodejs.md (references same commands)
        - Related: Issue #123 (API documentation overhaul)

  - type: textarea
    id: broken-links
    attributes:
      label: Broken Links / Examples (if applicable)
      description: List any broken links, failing code examples, or outdated references
      placeholder: |
        Example:
        - Link to https://old-domain.com/docs (404)
        - Code example at line 45 uses deprecated API
        - References removed feature "X"

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is this documentation for?
      options:
        - New Developers (Onboarding)
        - All Developers (Reference)
        - End Users
        - Administrators / DevOps
        - Contributors (Open Source)
        - Multiple Audiences
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help improve the documentation
      placeholder: |
        - Screenshots showing confusion
        - Questions from team members
        - Common misunderstandings
        - Feedback from users

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to contribute?
      description: Are you willing to help fix this documentation?
      options:
        - label: I'd like to submit a PR with the fix
        - label: I can review documentation changes
        - label: I can provide additional examples
        - label: I can test the updated documentation

  - type: markdown
    attributes:
      value: |
        ---

        ## Documentation Standards

        When fixing documentation, please follow:
        - **Clarity**: Use simple, direct language
        - **Completeness**: Include all necessary information
        - **Examples**: Provide working code examples
        - **Maintenance**: Keep it up-to-date with code changes
        - **Structure**: Follow our documentation guide (`.claude/rules/documentation-guide.md`)

        See `.claude/README.md` for guide descriptions and maintenance procedures.

        Thank you for helping improve our documentation!