name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for Contributing!

        We welcome feature suggestions that improve the application. Please:
        - Search [existing feature requests](../../issues?q=is%3Aissue+label%3Aenhancement) first
        - Submit one feature per request
        - Focus on the problem you're solving, not just the solution

        **Planning Reference**: See `.claude/rules/project-management.md` and `.claude/rules/product-development.md` for how features are evaluated and implemented.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
        - label: I have searched for existing feature requests and this is not a duplicate
          required: true
        - label: I am requesting a single feature, not multiple features combined
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        What problem does this feature solve? Focus on the **why**, not the **how**.
        Help us understand the workflow challenge or pain point you're experiencing.
      placeholder: |
        Example: As a user, I need to export my data to CSV, but currently there's no way to do this without manually copying from the UI. This makes it difficult to use the data in external tools or create backups.
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Who Benefits?
      description: Which user group would benefit from this feature?
      options:
        - End Users
        - Administrators
        - Developers/API Consumers
        - All Users
        - Other
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Describe your ideal solution. What would the user experience be?
        Be specific about UI, API endpoints, or behavior changes.
      placeholder: |
        Example:
        1. Add an "Export to CSV" button on the data table
        2. When clicked, download a CSV file with all visible columns
        3. Include filters/sorts applied by the user
        4. Show a success notification when complete
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application would this affect?
      options:
        - Frontend (React/MUI)
        - Backend API (Express)
        - Database Schema
        - Authentication/Authorization
        - Build/Deploy/DevOps
        - Testing
        - Documentation
        - Multiple Components
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Assessment)
      description: |
        How important is this feature to you?
        We'll use RICE scoring for final prioritization (see `.claude/rules/product-development.md`)
      options:
        - Critical - Blocking important work
        - High - Would significantly improve workflow
        - Medium - Nice to have, would help
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases / User Stories
      description: |
        Provide specific examples of how users would interact with this feature
        Use format: "As a [role], I want to [action], so that [benefit]"
      placeholder: |
        1. As an administrator, I want to export user activity logs to CSV, so that I can analyze usage patterns in Excel

        2. As a power user, I want to export filtered data, so that I can create custom reports for my team

        3. As a compliance officer, I want to export audit trails, so that I can meet regulatory requirements

  - type: input
    id: reach
    attributes:
      label: Estimated User Reach
      description: Approximately how many users would benefit? (for RICE scoring)
      placeholder: "Example: 500 users per month"

  - type: dropdown
    id: impact
    attributes:
      label: Impact (if implemented)
      description: How much would this improve the user experience?
      options:
        - "3 - Massive impact (game-changing)"
        - "2 - High impact (significantly better)"
        - "1 - Medium impact (noticeable improvement)"
        - "0.5 - Low impact (minor convenience)"
        - "0.25 - Minimal impact (nice detail)"

  - type: input
    id: effort
    attributes:
      label: Estimated Effort (Your Guess)
      description: How complex do you think this is? (We'll verify during planning)
      placeholder: "Example: Small (1-2 days), Medium (1 week), Large (2+ weeks)"

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions Considered
      description: |
        Have you tried other approaches or workarounds?
        Are there similar features in other tools you've used?
      placeholder: |
        Example:
        - Currently copying table data manually (very time-consuming)
        - Could use browser extensions but they don't work reliably
        - Similar feature in [Tool X] works like this: [description]

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Considerations (Optional)
      description: |
        Any technical details, constraints, or suggestions?
        Only if you have relevant technical knowledge - otherwise skip this.
      placeholder: |
        Example:
        - Could use csv-parser npm package
        - May need to handle large datasets (10k+ rows) with streaming
        - Should respect existing column permissions

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria (Optional)
      description: |
        What would need to be true for you to consider this feature "done"?
        This helps us understand your expectations.
      placeholder: |
        - [ ] Export button visible on all data tables
        - [ ] CSV includes all visible columns
        - [ ] Respects user's current filters and sorting
        - [ ] Works with datasets up to 10,000 rows
        - [ ] Includes proper error handling for failed exports
        - [ ] Shows success notification when complete

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: |
        Visual examples help us understand your vision
        - Screenshots from other tools
        - Wireframes or mockups
        - Example API requests/responses
      placeholder: "Attach images or describe visual design"

  - type: dropdown
    id: breaking-change
    attributes:
      label: Would this be a breaking change?
      description: Does this change existing behavior or APIs?
      options:
        - "No - Pure addition"
        - "Maybe - Changes existing feature"
        - "Yes - Breaks existing behavior"
        - "Unknown"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help us understand this request
      placeholder: |
        - Links to related discussions
        - References to similar features elsewhere
        - Business context or deadlines
        - Regulatory requirements

  - type: markdown
    attributes:
      value: |
        ---

        ## What Happens Next?

        1. **Triage**: We'll review this request within 1 week
        2. **RICE Scoring**: Feature will be scored for priority (Reach × Impact × Confidence / Effort)
        3. **Product Planning**: High-scoring features added to roadmap
        4. **Implementation**: Features implemented following our development lifecycle (`.claude/rules/project-management.md`)
        5. **Release**: Announced in changelog with documentation

        See `.claude/rules/product-development.md` for details on our product development process.

        Thank you for your suggestion!